/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CategoriesGet200Response,
  CategoriesTreeJsonGet200Response,
  MainErrorResponse,
} from '../models/index';
import {
    CategoriesGet200ResponseFromJSON,
    CategoriesGet200ResponseToJSON,
    CategoriesTreeJsonGet200ResponseFromJSON,
    CategoriesTreeJsonGet200ResponseToJSON,
    MainErrorResponseFromJSON,
    MainErrorResponseToJSON,
} from '../models/index';

export interface CategoriesGetRequest {
    category: string;
    page?: number;
}

/**
 * 
 */
export class CategoriesApi extends runtime.BaseAPI {

    /**
     * Get paginated post previews for a specific category
     * Get posts by category
     */
    async categoriesGetRaw(requestParameters: CategoriesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CategoriesGet200Response>> {
        if (requestParameters['category'] == null) {
            throw new runtime.RequiredError(
                'category',
                'Required parameter "category" was null or undefined when calling categoriesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['category'] != null) {
            queryParameters['category'] = requestParameters['category'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/categories`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CategoriesGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get paginated post previews for a specific category
     * Get posts by category
     */
    async categoriesGet(requestParameters: CategoriesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CategoriesGet200Response> {
        const response = await this.categoriesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get hierarchical category tree structure
     * Get category tree
     */
    async categoriesTreeJsonGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CategoriesTreeJsonGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/categories/tree.json`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CategoriesTreeJsonGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get hierarchical category tree structure
     * Get category tree
     */
    async categoriesTreeJsonGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CategoriesTreeJsonGet200Response> {
        const response = await this.categoriesTreeJsonGetRaw(initOverrides);
        return await response.value();
    }

}
