/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MainMetadataResponse,
} from '../models/index';
import {
    MainMetadataResponseFromJSON,
    MainMetadataResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class MetadataApi extends runtime.BaseAPI {

    /**
     * Get unified API metadata including counts, pagination info, and configuration
     * Get API metadata
     */
    async metaJsonGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MainMetadataResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/meta.json`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MainMetadataResponseFromJSON(jsonValue));
    }

    /**
     * Get unified API metadata including counts, pagination info, and configuration
     * Get API metadata
     */
    async metaJsonGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MainMetadataResponse> {
        const response = await this.metaJsonGetRaw(initOverrides);
        return await response.value();
    }

}
