/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MainErrorResponse,
  MainPostsResponse,
} from '../models/index';
import {
    MainErrorResponseFromJSON,
    MainErrorResponseToJSON,
    MainPostsResponseFromJSON,
    MainPostsResponseToJSON,
} from '../models/index';

export interface PostsGetRequest {
    slug?: string;
    page?: number;
}

/**
 * 
 */
export class PostsApi extends runtime.BaseAPI {

    /**
     * Get all posts or filter by slug/page
     * Get all posts
     */
    async postsGetRaw(requestParameters: PostsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MainPostsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['slug'] != null) {
            queryParameters['slug'] = requestParameters['slug'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/posts`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MainPostsResponseFromJSON(jsonValue));
    }

    /**
     * Get all posts or filter by slug/page
     * Get all posts
     */
    async postsGet(requestParameters: PostsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MainPostsResponse> {
        const response = await this.postsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
