/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MainErrorResponse,
  PostsByPageGet200Response,
  PostsBySlugGet200Response,
} from '../models/index';
import {
    MainErrorResponseFromJSON,
    MainErrorResponseToJSON,
    PostsByPageGet200ResponseFromJSON,
    PostsByPageGet200ResponseToJSON,
    PostsBySlugGet200ResponseFromJSON,
    PostsBySlugGet200ResponseToJSON,
} from '../models/index';

export interface PostsByPageGetRequest {
    page?: number;
}

export interface PostsBySlugGetRequest {
    slug: string;
}

/**
 * 
 */
export class PostsApi extends runtime.BaseAPI {

    /**
     * Get paginated posts with optional page parameter
     * Get paginated posts
     */
    async postsByPageGetRaw(requestParameters: PostsByPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostsByPageGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/posts/by-page`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostsByPageGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get paginated posts with optional page parameter
     * Get paginated posts
     */
    async postsByPageGet(requestParameters: PostsByPageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostsByPageGet200Response> {
        const response = await this.postsByPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a specific post by its slug
     * Get post by slug
     */
    async postsBySlugGetRaw(requestParameters: PostsBySlugGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostsBySlugGet200Response>> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling postsBySlugGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['slug'] != null) {
            queryParameters['slug'] = requestParameters['slug'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/posts/by-slug`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostsBySlugGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get a specific post by its slug
     * Get post by slug
     */
    async postsBySlugGet(requestParameters: PostsBySlugGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostsBySlugGet200Response> {
        const response = await this.postsBySlugGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
