/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MainErrorResponse,
  MainPreviewsResponse,
} from '../models/index';
import {
    MainErrorResponseFromJSON,
    MainErrorResponseToJSON,
    MainPreviewsResponseFromJSON,
    MainPreviewsResponseToJSON,
} from '../models/index';

export interface PreviewsGetRequest {
    slug?: string;
    page?: number;
}

/**
 * 
 */
export class PreviewsApi extends runtime.BaseAPI {

    /**
     * Get all post previews or filter by slug/page
     * Get all post previews
     */
    async previewsGetRaw(requestParameters: PreviewsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MainPreviewsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['slug'] != null) {
            queryParameters['slug'] = requestParameters['slug'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/previews`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MainPreviewsResponseFromJSON(jsonValue));
    }

    /**
     * Get all post previews or filter by slug/page
     * Get all post previews
     */
    async previewsGet(requestParameters: PreviewsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MainPreviewsResponse> {
        const response = await this.previewsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
