/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MainErrorResponse,
  MainRelatedPost,
} from '../models/index';
import {
    MainErrorResponseFromJSON,
    MainErrorResponseToJSON,
    MainRelatedPostFromJSON,
    MainRelatedPostToJSON,
} from '../models/index';

export interface RelatedGetRequest {
    slug?: string;
}

/**
 * 
 */
export class RelatedApi extends runtime.BaseAPI {

    /**
     * Get related posts for all posts or for a specific post
     * Get related posts
     */
    async relatedGetRaw(requestParameters: RelatedGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MainRelatedPost>>> {
        const queryParameters: any = {};

        if (requestParameters['slug'] != null) {
            queryParameters['slug'] = requestParameters['slug'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/related`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MainRelatedPostFromJSON));
    }

    /**
     * Get related posts for all posts or for a specific post
     * Get related posts
     */
    async relatedGet(requestParameters: RelatedGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MainRelatedPost>> {
        const response = await this.relatedGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
