/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MainErrorResponse,
  RelatedGet200Response,
} from '../models/index';
import {
    MainErrorResponseFromJSON,
    MainErrorResponseToJSON,
    RelatedGet200ResponseFromJSON,
    RelatedGet200ResponseToJSON,
} from '../models/index';

export interface RelatedGetRequest {
    slug: string;
}

/**
 * 
 */
export class RelatedApi extends runtime.BaseAPI {

    /**
     * Get related posts for a specific post by slug
     * Get related posts
     */
    async relatedGetRaw(requestParameters: RelatedGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RelatedGet200Response>> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling relatedGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['slug'] != null) {
            queryParameters['slug'] = requestParameters['slug'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/related`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RelatedGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get related posts for a specific post by slug
     * Get related posts
     */
    async relatedGet(requestParameters: RelatedGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RelatedGet200Response> {
        const response = await this.relatedGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
