/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SearchIndexJsonGet200Response,
} from '../models/index';
import {
    SearchIndexJsonGet200ResponseFromJSON,
    SearchIndexJsonGet200ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class SearchApi extends runtime.BaseAPI {

    /**
     * Get inverted search index for client-side search
     * Get search index
     */
    async searchIndexJsonGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchIndexJsonGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/search/index.json`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchIndexJsonGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get inverted search index for client-side search
     * Get search index
     */
    async searchIndexJsonGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchIndexJsonGet200Response> {
        const response = await this.searchIndexJsonGetRaw(initOverrides);
        return await response.value();
    }

}
