/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CategoriesGet200Response,
  MainErrorResponse,
} from '../models/index';
import {
    CategoriesGet200ResponseFromJSON,
    CategoriesGet200ResponseToJSON,
    MainErrorResponseFromJSON,
    MainErrorResponseToJSON,
} from '../models/index';

export interface TagsGetRequest {
    tag: string;
    page?: number;
}

/**
 * 
 */
export class TagsApi extends runtime.BaseAPI {

    /**
     * Get paginated post previews for a specific tag
     * Get posts by tag
     */
    async tagsGetRaw(requestParameters: TagsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CategoriesGet200Response>> {
        if (requestParameters['tag'] == null) {
            throw new runtime.RequiredError(
                'tag',
                'Required parameter "tag" was null or undefined when calling tagsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['tag'] != null) {
            queryParameters['tag'] = requestParameters['tag'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tags`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CategoriesGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get paginated post previews for a specific tag
     * Get posts by tag
     */
    async tagsGet(requestParameters: TagsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CategoriesGet200Response> {
        const response = await this.tagsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
