/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MainCategoryTreeNode } from './MainCategoryTreeNode';
import {
    MainCategoryTreeNodeFromJSON,
    MainCategoryTreeNodeFromJSONTyped,
    MainCategoryTreeNodeToJSON,
    MainCategoryTreeNodeToJSONTyped,
} from './MainCategoryTreeNode';

/**
 * 
 * @export
 * @interface CategoriesTreeJsonGet200Response
 */
export interface CategoriesTreeJsonGet200Response {
    /**
     * Hierarchical category tree structure
     * @type {Array<MainCategoryTreeNode>}
     * @memberof CategoriesTreeJsonGet200Response
     */
    data?: Array<MainCategoryTreeNode>;
}

/**
 * Check if a given object implements the CategoriesTreeJsonGet200Response interface.
 */
export function instanceOfCategoriesTreeJsonGet200Response(value: object): value is CategoriesTreeJsonGet200Response {
    return true;
}

export function CategoriesTreeJsonGet200ResponseFromJSON(json: any): CategoriesTreeJsonGet200Response {
    return CategoriesTreeJsonGet200ResponseFromJSONTyped(json, false);
}

export function CategoriesTreeJsonGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoriesTreeJsonGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(MainCategoryTreeNodeFromJSON)),
    };
}

export function CategoriesTreeJsonGet200ResponseToJSON(json: any): CategoriesTreeJsonGet200Response {
    return CategoriesTreeJsonGet200ResponseToJSONTyped(json, false);
}

export function CategoriesTreeJsonGet200ResponseToJSONTyped(value?: CategoriesTreeJsonGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(MainCategoryTreeNodeToJSON)),
    };
}

