/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MainPaginationInfo } from './MainPaginationInfo';
import {
    MainPaginationInfoFromJSON,
    MainPaginationInfoFromJSONTyped,
    MainPaginationInfoToJSON,
    MainPaginationInfoToJSONTyped,
} from './MainPaginationInfo';
import type { MainPostPreview } from './MainPostPreview';
import {
    MainPostPreviewFromJSON,
    MainPostPreviewFromJSONTyped,
    MainPostPreviewToJSON,
    MainPostPreviewToJSONTyped,
} from './MainPostPreview';

/**
 * 
 * @export
 * @interface CategoriesGet200Response
 */
export interface CategoriesGet200Response {
    /**
     * 
     * @type {Array<MainPostPreview>}
     * @memberof CategoriesGet200Response
     */
    data?: Array<MainPostPreview>;
    /**
     * 
     * @type {MainPaginationInfo}
     * @memberof CategoriesGet200Response
     */
    pagination?: MainPaginationInfo;
}

/**
 * Check if a given object implements the CategoriesGet200Response interface.
 */
export function instanceOfCategoriesGet200Response(value: object): value is CategoriesGet200Response {
    return true;
}

export function CategoriesGet200ResponseFromJSON(json: any): CategoriesGet200Response {
    return CategoriesGet200ResponseFromJSONTyped(json, false);
}

export function CategoriesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoriesGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(MainPostPreviewFromJSON)),
        'pagination': json['pagination'] == null ? undefined : MainPaginationInfoFromJSON(json['pagination']),
    };
}

export function CategoriesGet200ResponseToJSON(json: any): CategoriesGet200Response {
    return CategoriesGet200ResponseToJSONTyped(json, false);
}

export function CategoriesGet200ResponseToJSONTyped(value?: CategoriesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(MainPostPreviewToJSON)),
        'pagination': MainPaginationInfoToJSON(value['pagination']),
    };
}

