/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MainMetadataResponsePreviews
 */
export interface MainMetadataResponsePreviews {
    /**
     * 
     * @type {number}
     * @memberof MainMetadataResponsePreviews
     */
    perPage?: number;
    /**
     * 
     * @type {number}
     * @memberof MainMetadataResponsePreviews
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof MainMetadataResponsePreviews
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the MainMetadataResponsePreviews interface.
 */
export function instanceOfMainMetadataResponsePreviews(value: object): value is MainMetadataResponsePreviews {
    return true;
}

export function MainMetadataResponsePreviewsFromJSON(json: any): MainMetadataResponsePreviews {
    return MainMetadataResponsePreviewsFromJSONTyped(json, false);
}

export function MainMetadataResponsePreviewsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainMetadataResponsePreviews {
    if (json == null) {
        return json;
    }
    return {
        
        'perPage': json['perPage'] == null ? undefined : json['perPage'],
        'total': json['total'] == null ? undefined : json['total'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function MainMetadataResponsePreviewsToJSON(json: any): MainMetadataResponsePreviews {
    return MainMetadataResponsePreviewsToJSONTyped(json, false);
}

export function MainMetadataResponsePreviewsToJSONTyped(value?: MainMetadataResponsePreviews | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'perPage': value['perPage'],
        'total': value['total'],
        'totalPages': value['totalPages'],
    };
}

