/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pagination information for responses
 * @export
 * @interface MainPaginationInfo
 */
export interface MainPaginationInfo {
    /**
     * 
     * @type {boolean}
     * @memberof MainPaginationInfo
     */
    hasNext?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MainPaginationInfo
     */
    hasPrevious?: boolean;
    /**
     * 
     * @type {number}
     * @memberof MainPaginationInfo
     */
    nextPage?: number;
    /**
     * 
     * @type {number}
     * @memberof MainPaginationInfo
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof MainPaginationInfo
     */
    prevPage?: number;
    /**
     * 
     * @type {number}
     * @memberof MainPaginationInfo
     */
    totalItems?: number;
    /**
     * 
     * @type {number}
     * @memberof MainPaginationInfo
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the MainPaginationInfo interface.
 */
export function instanceOfMainPaginationInfo(value: object): value is MainPaginationInfo {
    return true;
}

export function MainPaginationInfoFromJSON(json: any): MainPaginationInfo {
    return MainPaginationInfoFromJSONTyped(json, false);
}

export function MainPaginationInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainPaginationInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'hasNext': json['hasNext'] == null ? undefined : json['hasNext'],
        'hasPrevious': json['hasPrevious'] == null ? undefined : json['hasPrevious'],
        'nextPage': json['nextPage'] == null ? undefined : json['nextPage'],
        'page': json['page'] == null ? undefined : json['page'],
        'prevPage': json['prevPage'] == null ? undefined : json['prevPage'],
        'totalItems': json['totalItems'] == null ? undefined : json['totalItems'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function MainPaginationInfoToJSON(json: any): MainPaginationInfo {
    return MainPaginationInfoToJSONTyped(json, false);
}

export function MainPaginationInfoToJSONTyped(value?: MainPaginationInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hasNext': value['hasNext'],
        'hasPrevious': value['hasPrevious'],
        'nextPage': value['nextPage'],
        'page': value['page'],
        'prevPage': value['prevPage'],
        'totalItems': value['totalItems'],
        'totalPages': value['totalPages'],
    };
}

