/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Hierarchical category tree node
 * @export
 * @interface MainCategoryTreeNode
 */
export interface MainCategoryTreeNode {
    /**
     * 
     * @type {Array<MainCategoryTreeNode>}
     * @memberof MainCategoryTreeNode
     */
    children?: Array<MainCategoryTreeNode>;
    /**
     * 
     * @type {string}
     * @memberof MainCategoryTreeNode
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof MainCategoryTreeNode
     */
    path?: string;
    /**
     * 
     * @type {number}
     * @memberof MainCategoryTreeNode
     */
    postCount?: number;
}

/**
 * Check if a given object implements the MainCategoryTreeNode interface.
 */
export function instanceOfMainCategoryTreeNode(value: object): value is MainCategoryTreeNode {
    return true;
}

export function MainCategoryTreeNodeFromJSON(json: any): MainCategoryTreeNode {
    return MainCategoryTreeNodeFromJSONTyped(json, false);
}

export function MainCategoryTreeNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainCategoryTreeNode {
    if (json == null) {
        return json;
    }
    return {
        
        'children': json['children'] == null ? undefined : ((json['children'] as Array<any>).map(MainCategoryTreeNodeFromJSON)),
        'name': json['name'] == null ? undefined : json['name'],
        'path': json['path'] == null ? undefined : json['path'],
        'postCount': json['postCount'] == null ? undefined : json['postCount'],
    };
}

export function MainCategoryTreeNodeToJSON(json: any): MainCategoryTreeNode {
    return MainCategoryTreeNodeToJSONTyped(json, false);
}

export function MainCategoryTreeNodeToJSONTyped(value?: MainCategoryTreeNode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'children': value['children'] == null ? undefined : ((value['children'] as Array<any>).map(MainCategoryTreeNodeToJSON)),
        'name': value['name'],
        'path': value['path'],
        'postCount': value['postCount'],
    };
}

