/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Standard single-item envelope
 * @export
 * @interface MainSingleResponse
 */
export interface MainSingleResponse {
    /**
     * 
     * @type {object}
     * @memberof MainSingleResponse
     */
    data?: object;
}

/**
 * Check if a given object implements the MainSingleResponse interface.
 */
export function instanceOfMainSingleResponse(value: object): value is MainSingleResponse {
    return true;
}

export function MainSingleResponseFromJSON(json: any): MainSingleResponse {
    return MainSingleResponseFromJSONTyped(json, false);
}

export function MainSingleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainSingleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function MainSingleResponseToJSON(json: any): MainSingleResponse {
    return MainSingleResponseToJSONTyped(json, false);
}

export function MainSingleResponseToJSONTyped(value?: MainSingleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

