/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Category information including hierarchy and post associations
 * @export
 * @interface MainCategoryInfo
 */
export interface MainCategoryInfo {
    /**
     * 
     * @type {Array<string>}
     * @memberof MainCategoryInfo
     */
    children?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof MainCategoryInfo
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof MainCategoryInfo
     */
    parent?: string;
    /**
     * 
     * @type {string}
     * @memberof MainCategoryInfo
     */
    path?: string;
    /**
     * 
     * @type {number}
     * @memberof MainCategoryInfo
     */
    postCount?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof MainCategoryInfo
     */
    postSlugs?: Array<string>;
}

/**
 * Check if a given object implements the MainCategoryInfo interface.
 */
export function instanceOfMainCategoryInfo(value: object): value is MainCategoryInfo {
    return true;
}

export function MainCategoryInfoFromJSON(json: any): MainCategoryInfo {
    return MainCategoryInfoFromJSONTyped(json, false);
}

export function MainCategoryInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainCategoryInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'children': json['children'] == null ? undefined : json['children'],
        'name': json['name'] == null ? undefined : json['name'],
        'parent': json['parent'] == null ? undefined : json['parent'],
        'path': json['path'] == null ? undefined : json['path'],
        'postCount': json['postCount'] == null ? undefined : json['postCount'],
        'postSlugs': json['postSlugs'] == null ? undefined : json['postSlugs'],
    };
}

export function MainCategoryInfoToJSON(json: any): MainCategoryInfo {
    return MainCategoryInfoToJSONTyped(json, false);
}

export function MainCategoryInfoToJSONTyped(value?: MainCategoryInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'children': value['children'],
        'name': value['name'],
        'parent': value['parent'],
        'path': value['path'],
        'postCount': value['postCount'],
        'postSlugs': value['postSlugs'],
    };
}

