/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MainMetadataResponsePosts
 */
export interface MainMetadataResponsePosts {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof MainMetadataResponsePosts
     */
    newest?: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof MainMetadataResponsePosts
     */
    oldest?: { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof MainMetadataResponsePosts
     */
    perPage?: number;
    /**
     * 
     * @type {number}
     * @memberof MainMetadataResponsePosts
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof MainMetadataResponsePosts
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the MainMetadataResponsePosts interface.
 */
export function instanceOfMainMetadataResponsePosts(value: object): value is MainMetadataResponsePosts {
    return true;
}

export function MainMetadataResponsePostsFromJSON(json: any): MainMetadataResponsePosts {
    return MainMetadataResponsePostsFromJSONTyped(json, false);
}

export function MainMetadataResponsePostsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainMetadataResponsePosts {
    if (json == null) {
        return json;
    }
    return {
        
        'newest': json['newest'] == null ? undefined : json['newest'],
        'oldest': json['oldest'] == null ? undefined : json['oldest'],
        'perPage': json['perPage'] == null ? undefined : json['perPage'],
        'total': json['total'] == null ? undefined : json['total'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function MainMetadataResponsePostsToJSON(json: any): MainMetadataResponsePosts {
    return MainMetadataResponsePostsToJSONTyped(json, false);
}

export function MainMetadataResponsePostsToJSONTyped(value?: MainMetadataResponsePosts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newest': value['newest'],
        'oldest': value['oldest'],
        'perPage': value['perPage'],
        'total': value['total'],
        'totalPages': value['totalPages'],
    };
}

