/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MainMetadataResponseCategories } from './MainMetadataResponseCategories';
import {
    MainMetadataResponseCategoriesFromJSON,
    MainMetadataResponseCategoriesFromJSONTyped,
    MainMetadataResponseCategoriesToJSON,
    MainMetadataResponseCategoriesToJSONTyped,
} from './MainMetadataResponseCategories';
import type { MainMetadataResponsePreviews } from './MainMetadataResponsePreviews';
import {
    MainMetadataResponsePreviewsFromJSON,
    MainMetadataResponsePreviewsFromJSONTyped,
    MainMetadataResponsePreviewsToJSON,
    MainMetadataResponsePreviewsToJSONTyped,
} from './MainMetadataResponsePreviews';
import type { MainMetadataResponseTags } from './MainMetadataResponseTags';
import {
    MainMetadataResponseTagsFromJSON,
    MainMetadataResponseTagsFromJSONTyped,
    MainMetadataResponseTagsToJSON,
    MainMetadataResponseTagsToJSONTyped,
} from './MainMetadataResponseTags';
import type { MainMetadataResponseConfig } from './MainMetadataResponseConfig';
import {
    MainMetadataResponseConfigFromJSON,
    MainMetadataResponseConfigFromJSONTyped,
    MainMetadataResponseConfigToJSON,
    MainMetadataResponseConfigToJSONTyped,
} from './MainMetadataResponseConfig';
import type { MainMetadataResponsePosts } from './MainMetadataResponsePosts';
import {
    MainMetadataResponsePostsFromJSON,
    MainMetadataResponsePostsFromJSONTyped,
    MainMetadataResponsePostsToJSON,
    MainMetadataResponsePostsToJSONTyped,
} from './MainMetadataResponsePosts';
import type { MainMetadataResponseRelated } from './MainMetadataResponseRelated';
import {
    MainMetadataResponseRelatedFromJSON,
    MainMetadataResponseRelatedFromJSONTyped,
    MainMetadataResponseRelatedToJSON,
    MainMetadataResponseRelatedToJSONTyped,
} from './MainMetadataResponseRelated';
import type { MainMetadataResponseSite } from './MainMetadataResponseSite';
import {
    MainMetadataResponseSiteFromJSON,
    MainMetadataResponseSiteFromJSONTyped,
    MainMetadataResponseSiteToJSON,
    MainMetadataResponseSiteToJSONTyped,
} from './MainMetadataResponseSite';

/**
 * Unified API metadata including counts, pagination info, and configuration
 * @export
 * @interface MainMetadataResponse
 */
export interface MainMetadataResponse {
    /**
     * 
     * @type {MainMetadataResponseCategories}
     * @memberof MainMetadataResponse
     */
    categories?: MainMetadataResponseCategories;
    /**
     * 
     * @type {MainMetadataResponseConfig}
     * @memberof MainMetadataResponse
     */
    config?: MainMetadataResponseConfig;
    /**
     * 
     * @type {MainMetadataResponsePosts}
     * @memberof MainMetadataResponse
     */
    posts?: MainMetadataResponsePosts;
    /**
     * 
     * @type {MainMetadataResponsePreviews}
     * @memberof MainMetadataResponse
     */
    previews?: MainMetadataResponsePreviews;
    /**
     * 
     * @type {MainMetadataResponseRelated}
     * @memberof MainMetadataResponse
     */
    related?: MainMetadataResponseRelated;
    /**
     * 
     * @type {MainMetadataResponseSite}
     * @memberof MainMetadataResponse
     */
    site?: MainMetadataResponseSite;
    /**
     * 
     * @type {MainMetadataResponseTags}
     * @memberof MainMetadataResponse
     */
    tags?: MainMetadataResponseTags;
}

/**
 * Check if a given object implements the MainMetadataResponse interface.
 */
export function instanceOfMainMetadataResponse(value: object): value is MainMetadataResponse {
    return true;
}

export function MainMetadataResponseFromJSON(json: any): MainMetadataResponse {
    return MainMetadataResponseFromJSONTyped(json, false);
}

export function MainMetadataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainMetadataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'categories': json['categories'] == null ? undefined : MainMetadataResponseCategoriesFromJSON(json['categories']),
        'config': json['config'] == null ? undefined : MainMetadataResponseConfigFromJSON(json['config']),
        'posts': json['posts'] == null ? undefined : MainMetadataResponsePostsFromJSON(json['posts']),
        'previews': json['previews'] == null ? undefined : MainMetadataResponsePreviewsFromJSON(json['previews']),
        'related': json['related'] == null ? undefined : MainMetadataResponseRelatedFromJSON(json['related']),
        'site': json['site'] == null ? undefined : MainMetadataResponseSiteFromJSON(json['site']),
        'tags': json['tags'] == null ? undefined : MainMetadataResponseTagsFromJSON(json['tags']),
    };
}

export function MainMetadataResponseToJSON(json: any): MainMetadataResponse {
    return MainMetadataResponseToJSONTyped(json, false);
}

export function MainMetadataResponseToJSONTyped(value?: MainMetadataResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'categories': MainMetadataResponseCategoriesToJSON(value['categories']),
        'config': MainMetadataResponseConfigToJSON(value['config']),
        'posts': MainMetadataResponsePostsToJSON(value['posts']),
        'previews': MainMetadataResponsePreviewsToJSON(value['previews']),
        'related': MainMetadataResponseRelatedToJSON(value['related']),
        'site': MainMetadataResponseSiteToJSON(value['site']),
        'tags': MainMetadataResponseTagsToJSON(value['tags']),
    };
}

