/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Tag information
 * @export
 * @interface MainTagInfo
 */
export interface MainTagInfo {
    /**
     * 
     * @type {string}
     * @memberof MainTagInfo
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof MainTagInfo
     */
    postCount?: number;
}

/**
 * Check if a given object implements the MainTagInfo interface.
 */
export function instanceOfMainTagInfo(value: object): value is MainTagInfo {
    return true;
}

export function MainTagInfoFromJSON(json: any): MainTagInfo {
    return MainTagInfoFromJSONTyped(json, false);
}

export function MainTagInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainTagInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'postCount': json['postCount'] == null ? undefined : json['postCount'],
    };
}

export function MainTagInfoToJSON(json: any): MainTagInfo {
    return MainTagInfoToJSONTyped(json, false);
}

export function MainTagInfoToJSONTyped(value?: MainTagInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'postCount': value['postCount'],
    };
}

