/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MainPaginationInfo } from './MainPaginationInfo';
import {
    MainPaginationInfoFromJSON,
    MainPaginationInfoFromJSONTyped,
    MainPaginationInfoToJSON,
    MainPaginationInfoToJSONTyped,
} from './MainPaginationInfo';

/**
 * Standard paginated list envelope
 * @export
 * @interface MainPaginatedResponse
 */
export interface MainPaginatedResponse {
    /**
     * 
     * @type {object}
     * @memberof MainPaginatedResponse
     */
    data?: object;
    /**
     * 
     * @type {MainPaginationInfo}
     * @memberof MainPaginatedResponse
     */
    pagination?: MainPaginationInfo;
}

/**
 * Check if a given object implements the MainPaginatedResponse interface.
 */
export function instanceOfMainPaginatedResponse(value: object): value is MainPaginatedResponse {
    return true;
}

export function MainPaginatedResponseFromJSON(json: any): MainPaginatedResponse {
    return MainPaginatedResponseFromJSONTyped(json, false);
}

export function MainPaginatedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainPaginatedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
        'pagination': json['pagination'] == null ? undefined : MainPaginationInfoFromJSON(json['pagination']),
    };
}

export function MainPaginatedResponseToJSON(json: any): MainPaginatedResponse {
    return MainPaginatedResponseToJSONTyped(json, false);
}

export function MainPaginatedResponseToJSONTyped(value?: MainPaginatedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'pagination': MainPaginationInfoToJSON(value['pagination']),
    };
}

