/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MainMetadataResponseSite
 */
export interface MainMetadataResponseSite {
    /**
     * 
     * @type {string}
     * @memberof MainMetadataResponseSite
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof MainMetadataResponseSite
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof MainMetadataResponseSite
     */
    tagline?: string;
}

/**
 * Check if a given object implements the MainMetadataResponseSite interface.
 */
export function instanceOfMainMetadataResponseSite(value: object): value is MainMetadataResponseSite {
    return true;
}

export function MainMetadataResponseSiteFromJSON(json: any): MainMetadataResponseSite {
    return MainMetadataResponseSiteFromJSONTyped(json, false);
}

export function MainMetadataResponseSiteFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainMetadataResponseSite {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'] == null ? undefined : json['name'],
        'tagline': json['tagline'] == null ? undefined : json['tagline'],
    };
}

export function MainMetadataResponseSiteToJSON(json: any): MainMetadataResponseSite {
    return MainMetadataResponseSiteToJSONTyped(json, false);
}

export function MainMetadataResponseSiteToJSONTyped(value?: MainMetadataResponseSite | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'name': value['name'],
        'tagline': value['tagline'],
    };
}

