/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MainMetadataResponseConfig
 */
export interface MainMetadataResponseConfig {
    /**
     * 
     * @type {string}
     * @memberof MainMetadataResponseConfig
     */
    dateFormat?: string;
    /**
     * 
     * @type {string}
     * @memberof MainMetadataResponseConfig
     */
    dateFormatReadable?: string;
}

/**
 * Check if a given object implements the MainMetadataResponseConfig interface.
 */
export function instanceOfMainMetadataResponseConfig(value: object): value is MainMetadataResponseConfig {
    return true;
}

export function MainMetadataResponseConfigFromJSON(json: any): MainMetadataResponseConfig {
    return MainMetadataResponseConfigFromJSONTyped(json, false);
}

export function MainMetadataResponseConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainMetadataResponseConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'dateFormat': json['dateFormat'] == null ? undefined : json['dateFormat'],
        'dateFormatReadable': json['dateFormatReadable'] == null ? undefined : json['dateFormatReadable'],
    };
}

export function MainMetadataResponseConfigToJSON(json: any): MainMetadataResponseConfig {
    return MainMetadataResponseConfigToJSONTyped(json, false);
}

export function MainMetadataResponseConfigToJSONTyped(value?: MainMetadataResponseConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dateFormat': value['dateFormat'],
        'dateFormatReadable': value['dateFormatReadable'],
    };
}

