/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MainMetadataResponseTags
 */
export interface MainMetadataResponseTags {
    /**
     * 
     * @type {number}
     * @memberof MainMetadataResponseTags
     */
    perPage?: number;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof MainMetadataResponseTags
     */
    stats?: { [key: string]: number; };
    /**
     * 
     * @type {number}
     * @memberof MainMetadataResponseTags
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof MainMetadataResponseTags
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the MainMetadataResponseTags interface.
 */
export function instanceOfMainMetadataResponseTags(value: object): value is MainMetadataResponseTags {
    return true;
}

export function MainMetadataResponseTagsFromJSON(json: any): MainMetadataResponseTags {
    return MainMetadataResponseTagsFromJSONTyped(json, false);
}

export function MainMetadataResponseTagsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainMetadataResponseTags {
    if (json == null) {
        return json;
    }
    return {
        
        'perPage': json['perPage'] == null ? undefined : json['perPage'],
        'stats': json['stats'] == null ? undefined : json['stats'],
        'total': json['total'] == null ? undefined : json['total'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function MainMetadataResponseTagsToJSON(json: any): MainMetadataResponseTags {
    return MainMetadataResponseTagsToJSONTyped(json, false);
}

export function MainMetadataResponseTagsToJSONTyped(value?: MainMetadataResponseTags | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'perPage': value['perPage'],
        'stats': value['stats'],
        'total': value['total'],
        'totalPages': value['totalPages'],
    };
}

