/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MainMetadataResponseRelated
 */
export interface MainMetadataResponseRelated {
    /**
     * 
     * @type {number}
     * @memberof MainMetadataResponseRelated
     */
    perPage?: number;
}

/**
 * Check if a given object implements the MainMetadataResponseRelated interface.
 */
export function instanceOfMainMetadataResponseRelated(value: object): value is MainMetadataResponseRelated {
    return true;
}

export function MainMetadataResponseRelatedFromJSON(json: any): MainMetadataResponseRelated {
    return MainMetadataResponseRelatedFromJSONTyped(json, false);
}

export function MainMetadataResponseRelatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainMetadataResponseRelated {
    if (json == null) {
        return json;
    }
    return {
        
        'perPage': json['perPage'] == null ? undefined : json['perPage'],
    };
}

export function MainMetadataResponseRelatedToJSON(json: any): MainMetadataResponseRelated {
    return MainMetadataResponseRelatedToJSONTyped(json, false);
}

export function MainMetadataResponseRelatedToJSONTyped(value?: MainMetadataResponseRelated | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'perPage': value['perPage'],
    };
}

