/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MainMetadataResponseCategories
 */
export interface MainMetadataResponseCategories {
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof MainMetadataResponseCategories
     */
    stats?: { [key: string]: number; };
    /**
     * 
     * @type {number}
     * @memberof MainMetadataResponseCategories
     */
    total?: number;
}

/**
 * Check if a given object implements the MainMetadataResponseCategories interface.
 */
export function instanceOfMainMetadataResponseCategories(value: object): value is MainMetadataResponseCategories {
    return true;
}

export function MainMetadataResponseCategoriesFromJSON(json: any): MainMetadataResponseCategories {
    return MainMetadataResponseCategoriesFromJSONTyped(json, false);
}

export function MainMetadataResponseCategoriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainMetadataResponseCategories {
    if (json == null) {
        return json;
    }
    return {
        
        'stats': json['stats'] == null ? undefined : json['stats'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function MainMetadataResponseCategoriesToJSON(json: any): MainMetadataResponseCategories {
    return MainMetadataResponseCategoriesToJSONTyped(json, false);
}

export function MainMetadataResponseCategoriesToJSONTyped(value?: MainMetadataResponseCategories | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stats': value['stats'],
        'total': value['total'],
    };
}

