/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Error response format
 * @export
 * @interface MainErrorResponse
 */
export interface MainErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof MainErrorResponse
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof MainErrorResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the MainErrorResponse interface.
 */
export function instanceOfMainErrorResponse(value: object): value is MainErrorResponse {
    return true;
}

export function MainErrorResponseFromJSON(json: any): MainErrorResponse {
    return MainErrorResponseFromJSONTyped(json, false);
}

export function MainErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function MainErrorResponseToJSON(json: any): MainErrorResponse {
    return MainErrorResponseToJSONTyped(json, false);
}

export function MainErrorResponseToJSONTyped(value?: MainErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'message': value['message'],
    };
}

