/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Post frontmatter containing metadata
 * @export
 * @interface MainFrontMatter
 */
export interface MainFrontMatter {
    /**
     * 
     * @type {string}
     * @memberof MainFrontMatter
     */
    author?: string;
    /**
     * 
     * @type {string}
     * @memberof MainFrontMatter
     */
    category?: string;
    /**
     * 
     * @type {string}
     * @memberof MainFrontMatter
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof MainFrontMatter
     */
    excerpt?: string;
    /**
     * 
     * @type {string}
     * @memberof MainFrontMatter
     */
    slug?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MainFrontMatter
     */
    tags?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof MainFrontMatter
     */
    title?: string;
}

/**
 * Check if a given object implements the MainFrontMatter interface.
 */
export function instanceOfMainFrontMatter(value: object): value is MainFrontMatter {
    return true;
}

export function MainFrontMatterFromJSON(json: any): MainFrontMatter {
    return MainFrontMatterFromJSONTyped(json, false);
}

export function MainFrontMatterFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainFrontMatter {
    if (json == null) {
        return json;
    }
    return {
        
        'author': json['author'] == null ? undefined : json['author'],
        'category': json['category'] == null ? undefined : json['category'],
        'date': json['date'] == null ? undefined : json['date'],
        'excerpt': json['excerpt'] == null ? undefined : json['excerpt'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function MainFrontMatterToJSON(json: any): MainFrontMatter {
    return MainFrontMatterToJSONTyped(json, false);
}

export function MainFrontMatterToJSONTyped(value?: MainFrontMatter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'author': value['author'],
        'category': value['category'],
        'date': value['date'],
        'excerpt': value['excerpt'],
        'slug': value['slug'],
        'tags': value['tags'],
        'title': value['title'],
    };
}

