/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Related post information with similarity metrics
 * @export
 * @interface MainRelatedPost
 */
export interface MainRelatedPost {
    /**
     * 
     * @type {number}
     * @memberof MainRelatedPost
     */
    commonTags?: number;
    /**
     * 
     * @type {string}
     * @memberof MainRelatedPost
     */
    date?: string;
    /**
     * 
     * @type {number}
     * @memberof MainRelatedPost
     */
    readingTime?: number;
    /**
     * 
     * @type {string}
     * @memberof MainRelatedPost
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof MainRelatedPost
     */
    title?: string;
}

/**
 * Check if a given object implements the MainRelatedPost interface.
 */
export function instanceOfMainRelatedPost(value: object): value is MainRelatedPost {
    return true;
}

export function MainRelatedPostFromJSON(json: any): MainRelatedPost {
    return MainRelatedPostFromJSONTyped(json, false);
}

export function MainRelatedPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainRelatedPost {
    if (json == null) {
        return json;
    }
    return {
        
        'commonTags': json['commonTags'] == null ? undefined : json['commonTags'],
        'date': json['date'] == null ? undefined : json['date'],
        'readingTime': json['readingTime'] == null ? undefined : json['readingTime'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function MainRelatedPostToJSON(json: any): MainRelatedPost {
    return MainRelatedPostToJSONTyped(json, false);
}

export function MainRelatedPostToJSONTyped(value?: MainRelatedPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'commonTags': value['commonTags'],
        'date': value['date'],
        'readingTime': value['readingTime'],
        'slug': value['slug'],
        'title': value['title'],
    };
}

