/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MainPostPreview } from './MainPostPreview';
import {
    MainPostPreviewFromJSON,
    MainPostPreviewFromJSONTyped,
    MainPostPreviewToJSON,
    MainPostPreviewToJSONTyped,
} from './MainPostPreview';

/**
 * Paginated response containing post previews and pagination metadata
 * @export
 * @interface MainPreviewsResponse
 */
export interface MainPreviewsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof MainPreviewsResponse
     */
    hasNext?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MainPreviewsResponse
     */
    hasPrevious?: boolean;
    /**
     * 
     * @type {number}
     * @memberof MainPreviewsResponse
     */
    nextPage?: number;
    /**
     * 
     * @type {number}
     * @memberof MainPreviewsResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof MainPreviewsResponse
     */
    prevPage?: number;
    /**
     * 
     * @type {Array<MainPostPreview>}
     * @memberof MainPreviewsResponse
     */
    previews?: Array<MainPostPreview>;
    /**
     * 
     * @type {number}
     * @memberof MainPreviewsResponse
     */
    totalItems?: number;
    /**
     * 
     * @type {number}
     * @memberof MainPreviewsResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the MainPreviewsResponse interface.
 */
export function instanceOfMainPreviewsResponse(value: object): value is MainPreviewsResponse {
    return true;
}

export function MainPreviewsResponseFromJSON(json: any): MainPreviewsResponse {
    return MainPreviewsResponseFromJSONTyped(json, false);
}

export function MainPreviewsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainPreviewsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'hasNext': json['hasNext'] == null ? undefined : json['hasNext'],
        'hasPrevious': json['hasPrevious'] == null ? undefined : json['hasPrevious'],
        'nextPage': json['nextPage'] == null ? undefined : json['nextPage'],
        'page': json['page'] == null ? undefined : json['page'],
        'prevPage': json['prevPage'] == null ? undefined : json['prevPage'],
        'previews': json['previews'] == null ? undefined : ((json['previews'] as Array<any>).map(MainPostPreviewFromJSON)),
        'totalItems': json['totalItems'] == null ? undefined : json['totalItems'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function MainPreviewsResponseToJSON(json: any): MainPreviewsResponse {
    return MainPreviewsResponseToJSONTyped(json, false);
}

export function MainPreviewsResponseToJSONTyped(value?: MainPreviewsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hasNext': value['hasNext'],
        'hasPrevious': value['hasPrevious'],
        'nextPage': value['nextPage'],
        'page': value['page'],
        'prevPage': value['prevPage'],
        'previews': value['previews'] == null ? undefined : ((value['previews'] as Array<any>).map(MainPostPreviewToJSON)),
        'totalItems': value['totalItems'],
        'totalPages': value['totalPages'],
    };
}

