/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MainCategoryInfo } from './MainCategoryInfo';
import {
    MainCategoryInfoFromJSON,
    MainCategoryInfoFromJSONTyped,
    MainCategoryInfoToJSON,
    MainCategoryInfoToJSONTyped,
} from './MainCategoryInfo';
import type { MainPost } from './MainPost';
import {
    MainPostFromJSON,
    MainPostFromJSONTyped,
    MainPostToJSON,
    MainPostToJSONTyped,
} from './MainPost';

/**
 * Category information with full post details
 * @export
 * @interface MainCategoryDetail
 */
export interface MainCategoryDetail {
    /**
     * 
     * @type {MainCategoryInfo}
     * @memberof MainCategoryDetail
     */
    info?: MainCategoryInfo;
    /**
     * 
     * @type {Array<MainPost>}
     * @memberof MainCategoryDetail
     */
    posts?: Array<MainPost>;
}

/**
 * Check if a given object implements the MainCategoryDetail interface.
 */
export function instanceOfMainCategoryDetail(value: object): value is MainCategoryDetail {
    return true;
}

export function MainCategoryDetailFromJSON(json: any): MainCategoryDetail {
    return MainCategoryDetailFromJSONTyped(json, false);
}

export function MainCategoryDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainCategoryDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'info': json['info'] == null ? undefined : MainCategoryInfoFromJSON(json['info']),
        'posts': json['posts'] == null ? undefined : ((json['posts'] as Array<any>).map(MainPostFromJSON)),
    };
}

export function MainCategoryDetailToJSON(json: any): MainCategoryDetail {
    return MainCategoryDetailToJSONTyped(json, false);
}

export function MainCategoryDetailToJSONTyped(value?: MainCategoryDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'info': MainCategoryInfoToJSON(value['info']),
        'posts': value['posts'] == null ? undefined : ((value['posts'] as Array<any>).map(MainPostToJSON)),
    };
}

