/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MainPost } from './MainPost';
import {
    MainPostFromJSON,
    MainPostFromJSONTyped,
    MainPostToJSON,
    MainPostToJSONTyped,
} from './MainPost';

/**
 * 
 * @export
 * @interface PostsBySlugGet200Response
 */
export interface PostsBySlugGet200Response {
    /**
     * 
     * @type {MainPost}
     * @memberof PostsBySlugGet200Response
     */
    data?: MainPost;
}

/**
 * Check if a given object implements the PostsBySlugGet200Response interface.
 */
export function instanceOfPostsBySlugGet200Response(value: object): value is PostsBySlugGet200Response {
    return true;
}

export function PostsBySlugGet200ResponseFromJSON(json: any): PostsBySlugGet200Response {
    return PostsBySlugGet200ResponseFromJSONTyped(json, false);
}

export function PostsBySlugGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostsBySlugGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : MainPostFromJSON(json['data']),
    };
}

export function PostsBySlugGet200ResponseToJSON(json: any): PostsBySlugGet200Response {
    return PostsBySlugGet200ResponseToJSONTyped(json, false);
}

export function PostsBySlugGet200ResponseToJSONTyped(value?: PostsBySlugGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': MainPostToJSON(value['data']),
    };
}

