/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MainPaginationInfo } from './MainPaginationInfo';
import {
    MainPaginationInfoFromJSON,
    MainPaginationInfoFromJSONTyped,
    MainPaginationInfoToJSON,
    MainPaginationInfoToJSONTyped,
} from './MainPaginationInfo';
import type { MainPost } from './MainPost';
import {
    MainPostFromJSON,
    MainPostFromJSONTyped,
    MainPostToJSON,
    MainPostToJSONTyped,
} from './MainPost';

/**
 * 
 * @export
 * @interface PostsByPageGet200Response
 */
export interface PostsByPageGet200Response {
    /**
     * 
     * @type {Array<MainPost>}
     * @memberof PostsByPageGet200Response
     */
    data?: Array<MainPost>;
    /**
     * 
     * @type {MainPaginationInfo}
     * @memberof PostsByPageGet200Response
     */
    pagination?: MainPaginationInfo;
}

/**
 * Check if a given object implements the PostsByPageGet200Response interface.
 */
export function instanceOfPostsByPageGet200Response(value: object): value is PostsByPageGet200Response {
    return true;
}

export function PostsByPageGet200ResponseFromJSON(json: any): PostsByPageGet200Response {
    return PostsByPageGet200ResponseFromJSONTyped(json, false);
}

export function PostsByPageGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostsByPageGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(MainPostFromJSON)),
        'pagination': json['pagination'] == null ? undefined : MainPaginationInfoFromJSON(json['pagination']),
    };
}

export function PostsByPageGet200ResponseToJSON(json: any): PostsByPageGet200Response {
    return PostsByPageGet200ResponseToJSONTyped(json, false);
}

export function PostsByPageGet200ResponseToJSONTyped(value?: PostsByPageGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(MainPostToJSON)),
        'pagination': MainPaginationInfoToJSON(value['pagination']),
    };
}

