/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MainPostPreview } from './MainPostPreview';
import {
    MainPostPreviewFromJSON,
    MainPostPreviewFromJSONTyped,
    MainPostPreviewToJSON,
    MainPostPreviewToJSONTyped,
} from './MainPostPreview';

/**
 * 
 * @export
 * @interface PreviewsBySlugGet200Response
 */
export interface PreviewsBySlugGet200Response {
    /**
     * 
     * @type {MainPostPreview}
     * @memberof PreviewsBySlugGet200Response
     */
    data?: MainPostPreview;
}

/**
 * Check if a given object implements the PreviewsBySlugGet200Response interface.
 */
export function instanceOfPreviewsBySlugGet200Response(value: object): value is PreviewsBySlugGet200Response {
    return true;
}

export function PreviewsBySlugGet200ResponseFromJSON(json: any): PreviewsBySlugGet200Response {
    return PreviewsBySlugGet200ResponseFromJSONTyped(json, false);
}

export function PreviewsBySlugGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreviewsBySlugGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : MainPostPreviewFromJSON(json['data']),
    };
}

export function PreviewsBySlugGet200ResponseToJSON(json: any): PreviewsBySlugGet200Response {
    return PreviewsBySlugGet200ResponseToJSONTyped(json, false);
}

export function PreviewsBySlugGet200ResponseToJSONTyped(value?: PreviewsBySlugGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': MainPostPreviewToJSON(value['data']),
    };
}

