/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MainPaginationInfo } from './MainPaginationInfo';
import {
    MainPaginationInfoFromJSON,
    MainPaginationInfoFromJSONTyped,
    MainPaginationInfoToJSON,
    MainPaginationInfoToJSONTyped,
} from './MainPaginationInfo';
import type { MainRelatedPost } from './MainRelatedPost';
import {
    MainRelatedPostFromJSON,
    MainRelatedPostFromJSONTyped,
    MainRelatedPostToJSON,
    MainRelatedPostToJSONTyped,
} from './MainRelatedPost';

/**
 * 
 * @export
 * @interface RelatedGet200Response
 */
export interface RelatedGet200Response {
    /**
     * 
     * @type {Array<MainRelatedPost>}
     * @memberof RelatedGet200Response
     */
    data?: Array<MainRelatedPost>;
    /**
     * 
     * @type {MainPaginationInfo}
     * @memberof RelatedGet200Response
     */
    pagination?: MainPaginationInfo;
}

/**
 * Check if a given object implements the RelatedGet200Response interface.
 */
export function instanceOfRelatedGet200Response(value: object): value is RelatedGet200Response {
    return true;
}

export function RelatedGet200ResponseFromJSON(json: any): RelatedGet200Response {
    return RelatedGet200ResponseFromJSONTyped(json, false);
}

export function RelatedGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelatedGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(MainRelatedPostFromJSON)),
        'pagination': json['pagination'] == null ? undefined : MainPaginationInfoFromJSON(json['pagination']),
    };
}

export function RelatedGet200ResponseToJSON(json: any): RelatedGet200Response {
    return RelatedGet200ResponseToJSONTyped(json, false);
}

export function RelatedGet200ResponseToJSONTyped(value?: RelatedGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(MainRelatedPostToJSON)),
        'pagination': MainPaginationInfoToJSON(value['pagination']),
    };
}

