/* tslint:disable */
/* eslint-disable */
/**
 * Mantle API
 * A static API for blogs that transforms markdown files with frontmatter into JSON endpoints
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchIndexJsonGet200Response
 */
export interface SearchIndexJsonGet200Response {
    /**
     * Inverted search index mapping terms to post slugs for client-side search
     * @type {{ [key: string]: Array<string>; }}
     * @memberof SearchIndexJsonGet200Response
     */
    data?: { [key: string]: Array<string>; };
}

/**
 * Check if a given object implements the SearchIndexJsonGet200Response interface.
 */
export function instanceOfSearchIndexJsonGet200Response(value: object): value is SearchIndexJsonGet200Response {
    return true;
}

export function SearchIndexJsonGet200ResponseFromJSON(json: any): SearchIndexJsonGet200Response {
    return SearchIndexJsonGet200ResponseFromJSONTyped(json, false);
}

export function SearchIndexJsonGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchIndexJsonGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function SearchIndexJsonGet200ResponseToJSON(json: any): SearchIndexJsonGet200Response {
    return SearchIndexJsonGet200ResponseToJSONTyped(json, false);
}

export function SearchIndexJsonGet200ResponseToJSONTyped(value?: SearchIndexJsonGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

